MODEL:
  NUM_CLASSES: 5
  BACKBONE:
    NAME: "Resnet50"
    OUT_CHANNELS: (512, 1024, 2048, 1024, 512, 256)
  RESNET:
    SE: False
    CBAM: False
    FUSION: False
    BLOCKS: [3, 4, 6, 3]
    EXTRAS: [512, 256, 128, 64]
  PRIORS:
    FEATURE_MAPS: [38, 19, 10, 5, 3, 1]
    STRIDES: [8, 16, 32, 64, 100, 300]
    MIN_SIZES: [15, 48, 78, 108, 138, 168]
    MAX_SIZES: [48, 78, 108, 138, 168, 180]
    ASPECT_RATIOS: [[1.5, 2, 3, 4], [1.5, 2, 3, 4], [1.5, 2, 3, 4], [1.5, 2, 3, 4], [1.5, 2, 3, 4], [1.5, 2, 3, 4]]
    BOXES_PER_LOCATION: [10, 10, 10, 10, 10, 10]
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("coco_2019_train",)
  TEST: ("coco_2019_val", )
SOLVER:
  MAX_ITER: 5000
  LR_STEPS: [2000, 4000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/test'