MODEL:
  NUM_CLASSES: 21
  BACKBONE:
    NAME: "R50_300"
    OUT_CHANNELS: (512, 1024, 2048, 1024, 512, 256)
  RESNET:
    SE: False
    CBAM: False
    FUSION: False
    BLOCKS: [3, 4, 6, 3]
    EXTRAS: [512, 256, 64, 64]
  PRIORS:
    FEATURE_MAPS: [38, 19, 10, 5, 3, 1]
    STRIDES: [8, 16, 32, 64, 100, 300]
    MIN_SIZES: [21, 45, 99, 153, 207, 261]
    MAX_SIZES: [45, 99, 153, 207, 261, 315]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/resnet50_ssd300_voc0712'